/**
 * Test Financial Data Broker + History Chart Engine Integration
 * 
 * Verifies that real financial data and historical charts are properly integrated
 * into v3-dev research reports, eliminating N/A fields and placeholder charts.
 */

const { buildResearchReport } = require('./services/reportService.js');

async function testFinancialIntegration() {
  console.log(`\n╔════════════════════════════════════════════════════════════════╗`);
  console.log(`║  Financial Data Broker + History Chart Engine Test - NVDA     ║`);
  console.log(`╚════════════════════════════════════════════════════════════════╝\n`);
  
  try {
    const symbol = 'NVDA';
    const assetType = 'equity';
    
    console.log(`🧪 [Test] Generating research report for ${symbol}...`);
    console.log(`   └─ Financial data should be populated from FinancialDataBroker`);
    console.log(`   └─ Historical charts should be generated by HistoryChartEngine\n`);
    
    const startTime = Date.now();
    const report = await buildResearchReport(symbol, assetType);
    const totalTime = Date.now() - startTime;
    
    console.log(`\n✅ [Test] Report generated successfully in ${totalTime}ms`);
    
    // ═══════════════════════════════════════════════════════════════
    // Test 1: Verify Financial Data Fields
    // ═══════════════════════════════════════════════════════════════
    console.log(`\n📊 [Test 1] Financial Data Verification`);
    
    const priceOK = report.price.last !== null;
    const marketCapOK = report.valuation.market_cap !== null;
    const peOK = report.valuation.pe_ttm !== null;
    const revenue5yOK = report.fundamentals.revenue_5y && report.fundamentals.revenue_5y.length > 0;
    const eps5yOK = report.fundamentals.eps_5y && report.fundamentals.eps_5y.length > 0;
    const roeOK = report.fundamentals.roe !== null;
    const roaOK = report.fundamentals.roa !== null;
    const revCAGROK = report.growth.revenue_cagr_3y !== null;
    const epsCAGROK = report.growth.eps_cagr_3y !== null;
    
    console.log(`   ├─ Price: ${report.price.last || 'N/A'} ${priceOK ? '✅' : '❌'}`);
    console.log(`   ├─ Market Cap: ${report.valuation.market_cap ? '$' + (report.valuation.market_cap / 1e9).toFixed(1) + 'B' : 'N/A'} ${marketCapOK ? '✅' : '❌'}`);
    console.log(`   ├─ PE TTM: ${report.valuation.pe_ttm || 'N/A'} ${peOK ? '✅' : '❌'}`);
    console.log(`   ├─ Revenue 5Y: ${revenue5yOK ? report.fundamentals.revenue_5y.length + ' periods' : 'N/A'} ${revenue5yOK ? '✅' : '❌'}`);
    console.log(`   ├─ EPS 5Y: ${eps5yOK ? report.fundamentals.eps_5y.length + ' periods' : 'N/A'} ${eps5yOK ? '✅' : '❌'}`);
    console.log(`   ├─ ROE: ${report.fundamentals.roe || 'N/A'} ${roeOK ? '✅' : '❌'}`);
    console.log(`   ├─ ROA: ${report.fundamentals.roa || 'N/A'} ${roaOK ? '✅' : '❌'}`);
    console.log(`   ├─ Revenue 3Y CAGR: ${revCAGROK ? report.growth.revenue_cagr_3y.toFixed(2) + '%' : 'N/A'} ${revCAGROK ? '✅' : '❌'}`);
    console.log(`   └─ EPS 3Y CAGR: ${epsCAGROK ? report.growth.eps_cagr_3y.toFixed(2) + '%' : 'N/A'} ${epsCAGROK ? '✅' : '❌'}`);
    
    // ═══════════════════════════════════════════════════════════════
    // Test 2: Verify Historical Charts
    // ═══════════════════════════════════════════════════════════════
    console.log(`\n📈 [Test 2] Historical Charts Verification`);
    
    const revenueChartOK = report.charts && report.charts.revenue_5y && 
                           report.charts.revenue_5y.startsWith('http');
    const epsChartOK = report.charts && report.charts.eps_5y && 
                       report.charts.eps_5y.startsWith('http');
    const financialTrendsOK = report.charts && report.charts.financial_trends && 
                              report.charts.financial_trends.startsWith('http');
    
    console.log(`   ├─ Revenue 5Y Chart: ${revenueChartOK ? report.charts.revenue_5y.substring(0, 60) + '...' : 'MISSING'} ${revenueChartOK ? '✅' : '❌'}`);
    console.log(`   ├─ EPS 5Y Chart: ${epsChartOK ? report.charts.eps_5y.substring(0, 60) + '...' : 'MISSING'} ${epsChartOK ? '✅' : '❌'}`);
    console.log(`   └─ Financial Trends Chart: ${financialTrendsOK ? report.charts.financial_trends.substring(0, 60) + '...' : 'MISSING'} ${financialTrendsOK ? '✅' : '❌'}`);
    
    // ═══════════════════════════════════════════════════════════════
    // Test 3: Check for N/A or Placeholder Content
    // ═══════════════════════════════════════════════════════════════
    console.log(`\n🔍 [Test 3] N/A and Placeholder Detection`);
    
    const reportJSON = JSON.stringify(report);
    
    // Count N/A occurrences (excluding expected places like segments)
    const naCount = (reportJSON.match(/"N\/A"/g) || []).length;
    const nullCount = (reportJSON.match(/:\s*null/g) || []).length;
    
    // Check for placeholder chart content
    const hasPlaceholder = /placeholder|Placeholder|PLACEHOLDER/i.test(reportJSON);
    
    console.log(`   ├─ "N/A" string occurrences: ${naCount} ${naCount === 0 ? '✅' : '⚠️'}`);
    console.log(`   ├─ null value occurrences: ${nullCount} ${nullCount < 50 ? '✅' : '⚠️ (many nulls)'}`);
    console.log(`   └─ Placeholder content: ${hasPlaceholder ? '❌ FOUND' : '✅ NONE'}`);
    
    // ═══════════════════════════════════════════════════════════════
    // Test 4: Detailed Historical Data Analysis
    // ═══════════════════════════════════════════════════════════════
    console.log(`\n📋 [Test 4] Historical Data Detail`);
    
    if (revenue5yOK) {
      console.log(`\n   Revenue 5Y Series:`);
      report.fundamentals.revenue_5y.forEach(entry => {
        console.log(`      ${entry.year}: $${(entry.value / 1e9).toFixed(2)}B`);
      });
    }
    
    if (eps5yOK) {
      console.log(`\n   EPS 5Y Series:`);
      report.fundamentals.eps_5y.forEach(entry => {
        console.log(`      ${entry.year}: $${entry.value.toFixed(2)}`);
      });
    }
    
    // ═══════════════════════════════════════════════════════════════
    // Final Score
    // ═══════════════════════════════════════════════════════════════
    console.log(`\n╔════════════════════════════════════════════════════════════════╗`);
    console.log(`║  ✅ Financial Data Broker + History Chart Engine Test Complete ║`);
    console.log(`╚════════════════════════════════════════════════════════════════╝\n`);
    
    const allChecks = [
      priceOK,
      marketCapOK,
      peOK,
      revenue5yOK,
      eps5yOK,
      roeOK,
      roaOK,
      revCAGROK,
      epsCAGROK,
      revenueChartOK,
      epsChartOK,
      financialTrendsOK
    ];
    
    const passedChecks = allChecks.filter(check => check).length;
    const totalChecks = allChecks.length;
    
    console.log(`\n📊 Final Score: ${passedChecks}/${totalChecks} checks passed`);
    
    if (passedChecks >= totalChecks - 2) {
      console.log(`\n✅ INTEGRATION SUCCESSFUL - Financial data and charts working!\n`);
    } else if (passedChecks >= totalChecks / 2) {
      console.log(`\n⚠️  PARTIAL SUCCESS - Some features working, review failures\n`);
    } else {
      console.log(`\n❌ INTEGRATION FAILED - Review module configuration\n`);
    }
    
  } catch (error) {
    console.error(`\n❌ [Test] Error: ${error.message}`);
    console.error(error.stack);
    process.exit(1);
  }
}

// Run test
testFinancialIntegration();
