/**
 * pdfTemplateUtils.js
 * 
 * Phase 6C: PDF 模板增强工具
 * 用于 Premium PDF - 专业封面、页眉、页脚、目录生成
 * 
 * 功能：
 * - 生成深蓝色机构级封面
 * - 添加页眉（USIS Institutional Research | SYMBOL | DATE）
 * - 添加页脚页码
 * - 自动生成目录（Table of Contents）
 */

/**
 * 安全设置字体（如果自定义字体不可用，回退到内置字体）
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {string} fontName - 字体名称（'Bold' 或 'Regular'）
 */
function safeSetFont(doc, fontName) {
  const hasBoldFont = doc._fontFamilies && doc._fontFamilies['Bold'];
  const hasRegularFont = doc._fontFamilies && doc._fontFamilies['Regular'];
  
  if (fontName === 'Bold') {
    doc.font(hasBoldFont ? 'Bold' : 'Helvetica-Bold');
  } else {
    doc.font(hasRegularFont ? 'Regular' : 'Helvetica');
  }
}

/**
 * 渲染专业封面页
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} report - 研报对象
 * @param {Object} options - 可选配置
 */
function renderProfessionalCover(doc, report, options = {}) {
  const {
    backgroundColor = '#1a2332', // 深蓝色背景
    accentColor = '#3b82f6',     // 蓝色强调
    textColor = '#ffffff',       // 白色文字
    logoPath = null,             // 可选 logo 路径
    firmName = null,             // 自定义机构名
    analystName = null           // 自定义分析师名
  } = options;
  
  console.log(`\n📘 [PDFTemplateUtils] Rendering professional cover page...`);
  console.log(`   ├─ Firm: ${firmName || 'USIS INSTITUTIONAL RESEARCH'}`);
  console.log(`   └─ Analyst: ${analystName || 'USIS Brain v7.7'}`);
  
  // 背景矩形（全页）
  doc.rect(0, 0, doc.page.width, doc.page.height)
     .fill(backgroundColor);
  
  // Logo（如果提供）
  if (logoPath) {
    try {
      doc.image(logoPath, 50, 50, { width: 100 });
    } catch (error) {
      console.warn(`⚠️  Logo load failed: ${error.message}`);
    }
  }
  
  // 机构名称（顶部）- 支持自定义
  const displayFirmName = firmName || 'USIS INSTITUTIONAL RESEARCH';
  doc.fontSize(14).fillColor(accentColor);
  safeSetFont(doc, 'Bold');
  doc.text(displayFirmName.toUpperCase(), 50, 120, { align: 'left' });
  
  // 分隔线
  doc.moveTo(50, 150)
     .lineTo(doc.page.width - 50, 150)
     .strokeColor(accentColor)
     .lineWidth(2)
     .stroke();
  
  // 主标题（股票代码）
  const symbol = report.symbol || 'N/A';
  doc.fontSize(56).fillColor(textColor);
  safeSetFont(doc, 'Bold');
  doc.text(symbol, 50, 220, { align: 'left' });
  
  // 副标题（公司名称或类型）
  const companyName = report.company_name || 'Equity Research Report';
  doc.fontSize(24).fillColor('#94a3b8'); // 浅灰色
  safeSetFont(doc, 'Regular');
  doc.text(companyName, 50, 300, { align: 'left', width: doc.page.width - 100 });
  
  // 报告类型标签
  doc.fontSize(14).fillColor(accentColor);
  safeSetFont(doc, 'Bold');
  doc.text('COMPREHENSIVE ANALYSIS REPORT', 50, 380, { align: 'left' });
  
  // 分析师信息 - 支持自定义
  const displayAnalyst = analystName || report.analyst || 'USIS Brain v7.7 Multi-AI System';
  doc.fontSize(12).fillColor('#94a3b8');
  safeSetFont(doc, 'Regular');
  doc.text(`Lead Analyst: ${displayAnalyst}`, 50, 420, { align: 'left' });
  
  // 评级（如果有）
  if (report.rating) {
    const ratingColors = {
      'Buy': '#10b981',
      'Strong Buy': '#059669',
      'Hold': '#f59e0b',
      'Sell': '#ef4444',
      'Strong Sell': '#dc2626'
    };
    
    const ratingColor = ratingColors[report.rating] || '#3b82f6';
    
    doc.fontSize(18).fillColor(ratingColor);
    safeSetFont(doc, 'Bold');
    doc.text(`Rating: ${report.rating}`, 50, 460, { align: 'left' });
  }
  
  // 目标价（如果有）
  if (report.targetPrice || report.target_price) {
    const target = report.targetPrice || report.target_price;
    doc.fontSize(16).fillColor(textColor);
    safeSetFont(doc, 'Bold');
    doc.text(`Target Price: ${target}`, 50, 500, { align: 'left' });
  }
  
  // 底部：日期和免责声明
  const reportDate = report.date || new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  doc.fontSize(12)
     .fillColor('#64748b')
  safeSetFont(doc, 'Regular');
  doc.text(reportDate, 50, doc.page.height - 150, { align: 'left' });
  
  doc.fontSize(9)
     .fillColor('#475569')
  doc.text(
       'This report is generated by USIS Brain v7.7 Multi-AI Research System.\n' +
       'For institutional use only. See full disclosures at the end of this report.',
       50,
       doc.page.height - 120,
       { align: 'left', width: doc.page.width - 100 }
     );
  
  // 底部装饰线
  doc.moveTo(50, doc.page.height - 50)
     .lineTo(doc.page.width - 50, doc.page.height - 50)
     .strokeColor(accentColor)
     .lineWidth(1)
     .stroke();
  
  console.log(`✅ [PDFTemplateUtils] Cover page rendered`);
  
  // 新页面开始正文
  doc.addPage();
}

/**
 * 生成目录（Table of Contents）
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Array} sections - 章节数组 [{title, page}]
 * @param {Object} options - 可选配置
 * @param {string} options.firmName - 🆕 v7.2: 机构名（用于溢出页页眉）
 * @param {number} options.pageNumber - 🆕 v7.2: 当前页码
 */
function renderTableOfContents(doc, sections, options = {}) {
  const {
    title = 'Table of Contents',
    startY = 60,  // 🆕 v7.2: 调整为60以适应页眉高度
    firmName = null,
    pageNumber = 2
  } = options;
  
  // 🆕 v7.2: 页码追踪（用于溢出页页眉）
  let currentPageNum = pageNumber;
  
  console.log(`\n📑 [PDFTemplateUtils] Rendering table of contents (${sections.length} sections)...`);
  
  // 标题
  doc.fontSize(24)
     .fillColor('#1a2332')
  safeSetFont(doc, 'Bold');
  doc.text(title, 50, startY, { align: 'left' });
  
  // 分隔线
  doc.moveTo(50, startY + 40)
     .lineTo(doc.page.width - 50, startY + 40)
     .strokeColor('#3b82f6')
     .lineWidth(2)
     .stroke();
  
  let currentY = startY + 70;
  
  // 遍历章节
  sections.forEach((section, index) => {
    // 检查是否需要分页
    if (currentY > doc.page.height - 100) {
      doc.addPage();
      currentPageNum++;
      
      // 🆕 v7.2: 溢出页添加机构页眉
      if (firmName) {
        renderInstitutionalHeader(doc, { firmName, pageNumber: currentPageNum });
      }
      
      currentY = 60; // 调整起始位置以适应页眉
    }
    
    // 章节编号
    const sectionNumber = (index + 1).toString().padStart(2, '0');
    doc.fontSize(12)
       .fillColor('#64748b')
  safeSetFont(doc, 'Bold');
  doc.text(sectionNumber, 50, currentY, { width: 30, continued: false });
    
    // 章节标题
    doc.fontSize(12)
       .fillColor('#1a2332')
  safeSetFont(doc, 'Regular');
  doc.text(section.title, 90, currentY, { width: doc.page.width - 200, continued: false });
    
    // 页码（右对齐）
    const pageNum = section.page || (index + 2);
    doc.fontSize(12)
       .fillColor('#64748b')
  safeSetFont(doc, 'Regular');
  doc.text(pageNum.toString(), doc.page.width - 100, currentY, { width: 50, align: 'right' });
    
    // 虚线连接
    const dotY = currentY + 5;
    for (let x = 90 + doc.widthOfString(section.title) + 10; x < doc.page.width - 110; x += 5) {
      doc.circle(x, dotY, 0.5).fill('#cbd5e1');
    }
    
    currentY += 25;
  });
  
  console.log(`✅ [PDFTemplateUtils] Table of contents rendered`);
  
  // 🆕 v7.2: 返回最终页码供调用者使用
  // 注意：移除了尾部 addPage()，由调用者控制分页
  return { finalPageNumber: currentPageNum };
}

/**
 * 添加页眉
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {string} symbol - 股票代码
 * @param {number} pageNumber - 页码
 * @param {Object} options - 可选配置
 */
function addHeader(doc, symbol, pageNumber, options = {}) {
  const {
    showOnFirstPage = false,
    headerText = 'USIS Institutional Research'
  } = options;
  
  // 第一页通常不显示页眉（封面）
  if (pageNumber === 1 && !showOnFirstPage) {
    return;
  }
  
  const currentY = doc.y; // 保存当前 Y 位置
  
  // 页眉文字
  doc.fontSize(9)
     .fillColor('#64748b')
  safeSetFont(doc, 'Regular');
  doc.text(
       `${headerText} | ${symbol} | ${new Date().toLocaleDateString('en-US')}`,
       50,
       30,
       { align: 'center', width: doc.page.width - 100 }
     );
  
  // 页眉分隔线
  doc.moveTo(50, 45)
     .lineTo(doc.page.width - 50, 45)
     .strokeColor('#e2e8f0')
     .lineWidth(0.5)
     .stroke();
  
  // 恢复 Y 位置
  doc.y = currentY;
}

/**
 * 🆕 v7.2: 渲染机构级页眉栏（蓝色顶栏）- 类似 DocRaptor Premium 样式
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} options - 配置选项
 * @param {string} options.firmName - 机构名称
 * @param {boolean} options.skipCover - 是否跳过封面页（默认 true）
 * @param {number} options.pageNumber - 当前页码
 */
function renderInstitutionalHeader(doc, options = {}) {
  const {
    firmName = 'Research',
    skipCover = true,
    pageNumber = 1,
    headerHeight = 28,
    backgroundColor = '#003366',
    gradientEnd = '#00509E'
  } = options;
  
  // 跳过封面页
  if (skipCover && pageNumber === 1) {
    return;
  }
  
  const currentY = doc.y;
  
  // 蓝色渐变背景栏
  doc.rect(0, 0, doc.page.width, headerHeight)
     .fill(backgroundColor);
  
  // 底部边框线
  doc.moveTo(0, headerHeight)
     .lineTo(doc.page.width, headerHeight)
     .strokeColor('#002244')
     .lineWidth(2)
     .stroke();
  
  // 页眉文字：机构名 — Equity Research
  const headerText = `${firmName} — Equity Research`;
  doc.fontSize(9)
     .fillColor('#ffffff');
  safeSetFont(doc, 'Bold');
  doc.text(headerText, 20, 9, { align: 'left' });
  
  // 恢复 Y 位置
  doc.y = currentY;
}

/**
 * 添加页脚（页码）
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {number} pageNumber - 页码
 * @param {number} totalPages - 总页数
 * @param {Object} options - 可选配置
 */
function addFooter(doc, pageNumber, totalPages, options = {}) {
  const {
    showOnFirstPage = false,
    includeDisclaimer = true
  } = options;
  
  // 第一页通常不显示页脚（封面）
  if (pageNumber === 1 && !showOnFirstPage) {
    return;
  }
  
  // 页脚分隔线
  doc.moveTo(50, doc.page.height - 70)
     .lineTo(doc.page.width - 50, doc.page.height - 70)
     .strokeColor('#e2e8f0')
     .lineWidth(0.5)
     .stroke();
  
  // 页码（居中）
  doc.fontSize(9)
     .fillColor('#64748b')
  safeSetFont(doc, 'Regular');
  doc.text(
       `Page ${pageNumber} of ${totalPages}`,
       50,
       doc.page.height - 55,
       { align: 'center', width: doc.page.width - 100 }
     );
  
  // 免责声明（可选）
  if (includeDisclaimer) {
    doc.fontSize(7)
       .fillColor('#94a3b8')
  doc.text(
         'Confidential - For institutional use only',
         50,
         doc.page.height - 35,
         { align: 'center', width: doc.page.width - 100 }
       );
  }
}

/**
 * 自动为 PDF 文档添加页眉页脚（简化版 - 不使用事件监听）
 * 注意：PDFKit 不支持自动页眉页脚，需要手动调用
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {string} symbol - 股票代码
 * @param {number} currentPage - 当前页码
 * @param {number} totalPages - 总页数
 * @param {Object} options - 可选配置
 */
function addPageHeaderFooter(doc, symbol, currentPage, totalPages, options = {}) {
  addHeader(doc, symbol, currentPage, options);
  addFooter(doc, currentPage, totalPages, options);
}

/**
 * 提取章节结构（用于目录生成）
 * @param {Object} report - 研报对象
 * @returns {Array} 章节数组 [{title, page}]
 */
function extractSections(report) {
  const sections = [];
  
  if (report.sections && Array.isArray(report.sections)) {
    report.sections.forEach((section, index) => {
      sections.push({
        title: section.title || section.heading || `Section ${index + 1}`,
        page: index + 2 // 假设封面是第1页，目录是第2页
      });
    });
  } else if (report.sections && typeof report.sections === 'object') {
    // 如果 sections 是对象
    Object.keys(report.sections).forEach((key, index) => {
      sections.push({
        title: report.sections[key].title || key,
        page: index + 2
      });
    });
  }
  
  return sections;
}

// ═══════════════════════════════════════════════════════════════
// 🆕 v7.2: V6 机构级排版组件（从 DocRaptor 移植到 PDFKit）
// ═══════════════════════════════════════════════════════════════

/**
 * 渲染 Key Takeaways 部分 - 两列布局（Key Messages | Key Risks）
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} data - 数据对象 { messages: [], risks: [] }
 * @param {Object} options - 配置选项
 */
function renderKeyTakeawaysSection(doc, data = {}, options = {}) {
  const { startY = 60 } = options;
  const messages = data.messages || [];
  const risks = data.risks || [];
  
  console.log(`📊 [PDFTemplateUtils] Rendering Key Takeaways section...`);
  
  // 标题
  doc.fontSize(18).fillColor('#1a2332');
  safeSetFont(doc, 'Bold');
  doc.text('Key Takeaways', 50, startY);
  
  // 分隔线
  doc.moveTo(50, startY + 25)
     .lineTo(doc.page.width - 50, startY + 25)
     .strokeColor('#3b82f6')
     .lineWidth(2)
     .stroke();
  
  const columnWidth = (doc.page.width - 120) / 2;
  const leftX = 50;
  const rightX = 50 + columnWidth + 20;
  let currentY = startY + 45;
  
  // 左列标题：Key Messages
  doc.fontSize(12).fillColor('#3b82f6');
  safeSetFont(doc, 'Bold');
  doc.text('Key Messages', leftX, currentY);
  
  // 右列标题：Key Risks
  doc.text('Key Risks', rightX, currentY);
  
  currentY += 25;
  
  // 左列内容：Messages
  doc.fontSize(9).fillColor('#374151');
  safeSetFont(doc, 'Regular');
  messages.slice(0, 4).forEach((msg, i) => {
    const bullet = `• ${msg.substring(0, 120)}${msg.length > 120 ? '...' : ''}`;
    doc.text(bullet, leftX, currentY + i * 35, { width: columnWidth - 10 });
  });
  
  // 右列内容：Risks
  risks.slice(0, 4).forEach((risk, i) => {
    const riskText = typeof risk === 'string' ? risk : (risk.description || risk.text || '');
    const bullet = `• ${riskText.substring(0, 120)}${riskText.length > 120 ? '...' : ''}`;
    doc.text(bullet, rightX, currentY + i * 35, { width: columnWidth - 10 });
  });
  
  console.log(`   └─ ✅ Key Takeaways rendered (${messages.length} messages, ${risks.length} risks)`);
  
  return currentY + 160; // 返回结束 Y 位置
}

/**
 * 渲染 Key Metrics 数据卡片行
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} metrics - 指标数据
 * @param {Object} options - 配置选项
 */
function renderKeyMetricsRow(doc, metrics = {}, options = {}) {
  const { startY = 60 } = options;
  
  console.log(`📊 [PDFTemplateUtils] Rendering Key Metrics row...`);
  
  // 标题
  doc.fontSize(18).fillColor('#1a2332');
  safeSetFont(doc, 'Bold');
  doc.text('Key Metrics', 50, startY);
  
  // 分隔线
  doc.moveTo(50, startY + 25)
     .lineTo(doc.page.width - 50, startY + 25)
     .strokeColor('#3b82f6')
     .lineWidth(2)
     .stroke();
  
  // 定义指标数据
  const metricsData = [
    { label: 'PE (TTM)', value: formatMetric(metrics.pe_ttm, 'x') },
    { label: 'PE (FWD)', value: formatMetric(metrics.pe_fwd, 'x') },
    { label: 'P/S', value: formatMetric(metrics.ps_ttm, 'x') },
    { label: 'BETA', value: formatMetric(metrics.beta, '') }
  ];
  
  const metricsData2 = [
    { label: '52W HIGH', value: formatMetric(metrics.high_52w, '$', true) },
    { label: '52W LOW', value: formatMetric(metrics.low_52w, '$', true) },
    { label: 'DIV YIELD', value: formatMetric(metrics.div_yield, '%') },
    { label: 'ROE', value: formatMetric(metrics.roe, '%') }
  ];
  
  const cardWidth = (doc.page.width - 140) / 4;
  const cardHeight = 50;
  let currentY = startY + 40;
  
  // 第一行卡片
  metricsData.forEach((item, i) => {
    const x = 50 + i * (cardWidth + 15);
    renderMetricCard(doc, x, currentY, cardWidth, cardHeight, item.label, item.value);
  });
  
  currentY += cardHeight + 15;
  
  // 第二行卡片
  metricsData2.forEach((item, i) => {
    const x = 50 + i * (cardWidth + 15);
    renderMetricCard(doc, x, currentY, cardWidth, cardHeight, item.label, item.value);
  });
  
  console.log(`   └─ ✅ Key Metrics rendered (8 cards)`);
  
  return currentY + cardHeight + 20;
}

/**
 * 渲染单个指标卡片
 */
function renderMetricCard(doc, x, y, width, height, label, value) {
  // 卡片背景
  doc.rect(x, y, width, height)
     .fillColor('#f8fafc')
     .fill();
  
  // 卡片边框
  doc.rect(x, y, width, height)
     .strokeColor('#e2e8f0')
     .lineWidth(1)
     .stroke();
  
  // 标签
  doc.fontSize(8).fillColor('#64748b');
  safeSetFont(doc, 'Regular');
  doc.text(label, x + 8, y + 8, { width: width - 16, align: 'center' });
  
  // 值
  doc.fontSize(14).fillColor('#1a2332');
  safeSetFont(doc, 'Bold');
  doc.text(value, x + 8, y + 25, { width: width - 16, align: 'center' });
}

/**
 * 格式化指标值
 */
function formatMetric(value, suffix = '', isCurrency = false) {
  if (value === null || value === undefined || isNaN(value)) return 'N/A';
  if (isCurrency) {
    return `$${Number(value).toFixed(2)}`;
  }
  return `${Number(value).toFixed(2)}${suffix}`;
}

/**
 * 渲染 Our View vs Consensus 对比表
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} data - 数据对象 { ourView: {}, consensus: {} }
 * @param {Object} options - 配置选项
 */
function renderConsensusTable(doc, data = {}, options = {}) {
  const { startY = 60 } = options;
  const ourView = data.ourView || {};
  const consensus = data.consensus || {};
  
  console.log(`📊 [PDFTemplateUtils] Rendering Consensus table...`);
  
  // 标题
  doc.fontSize(14).fillColor('#1a2332');
  safeSetFont(doc, 'Bold');
  doc.text('Our View vs Consensus', 50, startY);
  
  // 表格数据
  const rows = [
    { metric: 'EPS Growth (Next 12M)', our: formatMetric(ourView.epsGrowth, '%'), cons: consensus.epsGrowth || 'N/A' },
    { metric: 'ROE', our: formatMetric(ourView.roe, '%'), cons: consensus.roe || 'N/A' },
    { metric: 'Rating', our: ourView.rating || 'N/A', cons: consensus.rating || 'N/A' },
    { metric: 'Target Price', our: formatMetric(ourView.targetPrice, '$', true), cons: consensus.targetPrice || 'N/A' }
  ];
  
  const tableX = 50;
  const tableWidth = doc.page.width - 100;
  const colWidths = [tableWidth * 0.5, tableWidth * 0.25, tableWidth * 0.25];
  let currentY = startY + 25;
  
  // 表头
  doc.fontSize(9).fillColor('#64748b');
  safeSetFont(doc, 'Bold');
  doc.rect(tableX, currentY, tableWidth, 20).fillColor('#f1f5f9').fill();
  doc.fillColor('#64748b');
  doc.text('Metric', tableX + 10, currentY + 6, { width: colWidths[0] - 20 });
  doc.text('Our View', tableX + colWidths[0] + 10, currentY + 6, { width: colWidths[1] - 20, align: 'center' });
  doc.text('Consensus', tableX + colWidths[0] + colWidths[1] + 10, currentY + 6, { width: colWidths[2] - 20, align: 'center' });
  
  currentY += 20;
  
  // 表格行
  rows.forEach((row, i) => {
    const bgColor = i % 2 === 0 ? '#ffffff' : '#f8fafc';
    doc.rect(tableX, currentY, tableWidth, 22).fillColor(bgColor).fill();
    
    doc.fontSize(9).fillColor('#374151');
    safeSetFont(doc, 'Regular');
    doc.text(row.metric, tableX + 10, currentY + 6, { width: colWidths[0] - 20 });
    doc.text(row.our, tableX + colWidths[0] + 10, currentY + 6, { width: colWidths[1] - 20, align: 'center' });
    doc.text(row.cons, tableX + colWidths[0] + colWidths[1] + 10, currentY + 6, { width: colWidths[2] - 20, align: 'center' });
    
    currentY += 22;
  });
  
  // 表格边框
  doc.rect(tableX, startY + 25, tableWidth, currentY - startY - 25)
     .strokeColor('#e2e8f0')
     .lineWidth(1)
     .stroke();
  
  console.log(`   └─ ✅ Consensus table rendered`);
  
  return currentY + 10;
}

/**
 * 渲染样式化章节分隔标题
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {string} title - 章节标题
 * @param {Object} options - 配置选项
 */
function renderSectionDivider(doc, title, options = {}) {
  const { startY = 60, sectionNumber = null } = options;
  
  // 蓝色背景条
  doc.rect(50, startY, doc.page.width - 100, 30)
     .fillColor('#1a2332')
     .fill();
  
  // 章节编号（如果提供）
  if (sectionNumber) {
    doc.fontSize(11).fillColor('#3b82f6');
    safeSetFont(doc, 'Bold');
    doc.text(sectionNumber, 60, startY + 9);
  }
  
  // 章节标题
  doc.fontSize(12).fillColor('#ffffff');
  safeSetFont(doc, 'Bold');
  doc.text(title, sectionNumber ? 90 : 60, startY + 9);
  
  return startY + 40;
}

// ═══════════════════════════════════════════════════════════════
// 🆕 V6 完整布局组件 - 机构级20页报告支持
// ═══════════════════════════════════════════════════════════════

/**
 * 通用表格渲染器（带交替行颜色）
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} config - 表格配置
 */
function renderGenericTable(doc, config = {}) {
  const {
    startY = 60,
    headers = [],
    rows = [],
    columnWidths = null,
    title = null,
    showBorder = true
  } = config;
  
  let currentY = startY;
  const tableX = 50;
  const tableWidth = doc.page.width - 100;
  const numCols = headers.length || (rows[0] ? rows[0].length : 1);
  const colWidths = columnWidths || Array(numCols).fill(tableWidth / numCols);
  const rowHeight = 22;
  
  // 标题（如果提供）
  if (title) {
    doc.fontSize(14).fillColor('#1a2332');
    safeSetFont(doc, 'Bold');
    doc.text(title, tableX, currentY);
    currentY += 25;
  }
  
  // 表头
  if (headers.length > 0) {
    doc.rect(tableX, currentY, tableWidth, rowHeight + 2).fillColor('#1a2332').fill();
    doc.fontSize(9).fillColor('#ffffff');
    safeSetFont(doc, 'Bold');
    
    let colX = tableX;
    headers.forEach((header, i) => {
      doc.text(header, colX + 8, currentY + 6, { width: colWidths[i] - 16, align: i === 0 ? 'left' : 'center' });
      colX += colWidths[i];
    });
    currentY += rowHeight + 2;
  }
  
  // 数据行
  rows.forEach((row, rowIndex) => {
    const bgColor = rowIndex % 2 === 0 ? '#ffffff' : '#f8fafc';
    doc.rect(tableX, currentY, tableWidth, rowHeight).fillColor(bgColor).fill();
    
    doc.fontSize(9).fillColor('#374151');
    safeSetFont(doc, 'Regular');
    
    let colX = tableX;
    row.forEach((cell, i) => {
      const cellValue = cell === null || cell === undefined ? 'N/A' : String(cell);
      doc.text(cellValue, colX + 8, currentY + 6, { width: colWidths[i] - 16, align: i === 0 ? 'left' : 'center' });
      colX += colWidths[i];
    });
    currentY += rowHeight;
  });
  
  // 边框
  if (showBorder) {
    doc.rect(tableX, startY + (title ? 25 : 0), tableWidth, currentY - startY - (title ? 25 : 0))
       .strokeColor('#e2e8f0').lineWidth(1).stroke();
  }
  
  return currentY + 15;
}

/**
 * 两列布局渲染器
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} config - 配置
 */
function renderTwoColumnSection(doc, config = {}) {
  const {
    startY = 60,
    leftTitle = '',
    rightTitle = '',
    leftItems = [],
    rightItems = [],
    sectionTitle = null
  } = config;
  
  let currentY = startY;
  const columnWidth = (doc.page.width - 120) / 2;
  const leftX = 50;
  const rightX = 50 + columnWidth + 20;
  
  // 主标题（如果提供）
  if (sectionTitle) {
    doc.fontSize(18).fillColor('#1a2332');
    safeSetFont(doc, 'Bold');
    doc.text(sectionTitle, 50, currentY);
    
    doc.moveTo(50, currentY + 25).lineTo(doc.page.width - 50, currentY + 25)
       .strokeColor('#3b82f6').lineWidth(2).stroke();
    currentY += 45;
  }
  
  // 左列标题
  doc.fontSize(12).fillColor('#3b82f6');
  safeSetFont(doc, 'Bold');
  doc.text(leftTitle, leftX, currentY);
  doc.text(rightTitle, rightX, currentY);
  currentY += 25;
  
  // 计算最大行数
  const maxItems = Math.max(leftItems.length, rightItems.length);
  const itemHeight = 40;
  
  // 渲染左右列内容
  for (let i = 0; i < Math.min(maxItems, 6); i++) {
    const itemY = currentY + i * itemHeight;
    
    // 左列
    if (leftItems[i]) {
      doc.fontSize(9).fillColor('#374151');
      safeSetFont(doc, 'Regular');
      const text = typeof leftItems[i] === 'string' ? leftItems[i] : leftItems[i].text || '';
      doc.text(`• ${text.substring(0, 150)}${text.length > 150 ? '...' : ''}`, leftX, itemY, { width: columnWidth - 10 });
    }
    
    // 右列
    if (rightItems[i]) {
      doc.fontSize(9).fillColor('#374151');
      safeSetFont(doc, 'Regular');
      const text = typeof rightItems[i] === 'string' ? rightItems[i] : rightItems[i].text || '';
      doc.text(`• ${text.substring(0, 150)}${text.length > 150 ? '...' : ''}`, rightX, itemY, { width: columnWidth - 10 });
    }
  }
  
  return currentY + Math.min(maxItems, 6) * itemHeight + 20;
}

/**
 * 图表/图像框架渲染器
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} config - 配置
 */
function renderChartFrame(doc, config = {}) {
  const {
    startY = 60,
    title = 'Chart',
    imageData = null,
    imagePath = null,
    width = null,
    height = 200,
    placeholder = 'Chart data currently unavailable'
  } = config;
  
  let currentY = startY;
  const chartWidth = width || (doc.page.width - 100);
  const chartX = 50;
  
  // 标题
  doc.fontSize(12).fillColor('#1a2332');
  safeSetFont(doc, 'Bold');
  doc.text(title, chartX, currentY);
  currentY += 20;
  
  // 尝试渲染图像
  let imageRendered = false;
  
  if (imageData || imagePath) {
    try {
      const imgSource = imageData || imagePath;
      
      // 如果是 base64 数据 URL
      if (typeof imgSource === 'string' && imgSource.startsWith('data:')) {
        const base64Data = imgSource.split(',')[1];
        const buffer = Buffer.from(base64Data, 'base64');
        doc.image(buffer, chartX, currentY, { width: chartWidth, height: height });
        imageRendered = true;
      } 
      // 如果是 URL
      else if (typeof imgSource === 'string' && (imgSource.startsWith('http') || imgSource.startsWith('/'))) {
        doc.image(imgSource, chartX, currentY, { width: chartWidth, height: height });
        imageRendered = true;
      }
    } catch (error) {
      console.warn(`⚠️  Chart image render failed: ${error.message}`);
    }
  }
  
  // 占位符（如果图像渲染失败）
  if (!imageRendered) {
    doc.rect(chartX, currentY, chartWidth, height)
       .fillColor('#f8fafc').fill();
    doc.rect(chartX, currentY, chartWidth, height)
       .strokeColor('#e2e8f0').lineWidth(1).stroke();
    
    doc.fontSize(11).fillColor('#94a3b8');
    safeSetFont(doc, 'Regular');
    doc.text(placeholder, chartX, currentY + height / 2 - 10, { width: chartWidth, align: 'center' });
  }
  
  return currentY + height + 20;
}

/**
 * 项目符号列表渲染器
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} config - 配置
 */
function renderBulletList(doc, config = {}) {
  const {
    startY = 60,
    title = null,
    items = [],
    maxItems = 8,
    numbered = false,
    itemPrefix = null
  } = config;
  
  let currentY = startY;
  
  // 标题
  if (title) {
    doc.fontSize(14).fillColor('#1a2332');
    safeSetFont(doc, 'Bold');
    doc.text(title, 50, currentY);
    currentY += 25;
  }
  
  // 列表项
  doc.fontSize(10).fillColor('#374151');
  safeSetFont(doc, 'Regular');
  
  items.slice(0, maxItems).forEach((item, i) => {
    const text = typeof item === 'string' ? item : (item.text || item.description || '');
    const prefix = numbered ? `${i + 1}. ` : (itemPrefix ? `${itemPrefix} ${i + 1}: ` : '• ');
    const displayText = `${prefix}${text.substring(0, 350)}${text.length > 350 ? '...' : ''}`;
    
    doc.text(displayText, 50, currentY, { width: doc.page.width - 100 });
    currentY += doc.heightOfString(displayText, { width: doc.page.width - 100 }) + 8;
  });
  
  return currentY + 15;
}

/**
 * 估值快照表格
 */
function renderValuationSnapshot(doc, config = {}) {
  const { startY = 60, valuation = {}, price = {} } = config;
  
  const rows = [
    ['Price', formatMetricValue(price.last, '$'), `${formatMetricValue(price.low_52w, '$')} - ${formatMetricValue(price.high_52w, '$')}`],
    ['PE (TTM)', formatMetricValue(valuation.pe_ttm, 'x'), '-'],
    ['PE (Forward)', formatMetricValue(valuation.pe_forward, 'x'), '-'],
    ['P/S (TTM)', formatMetricValue(valuation.ps_ttm, 'x'), '-'],
    ['P/B', formatMetricValue(valuation.pb, 'x'), '-'],
    ['Dividend Yield', formatMetricValue(valuation.dividend_yield, '%'), '-'],
    ['EV/EBITDA', formatMetricValue(valuation.ev_ebitda, 'x'), '-']
  ];
  
  return renderGenericTable(doc, {
    startY,
    title: 'Valuation Snapshot',
    headers: ['Metric', 'Current', '52W Range'],
    rows,
    columnWidths: [200, 140, 155]
  });
}

/**
 * 同行比较表格
 */
function renderPeerComparison(doc, config = {}) {
  const { startY = 60, peers = [], symbol = '' } = config;
  
  const rows = peers.slice(0, 6).map(p => [
    p.name || p.symbol,
    p.symbol,
    formatLargeNumber(p.market_cap),
    formatMetricValue(p.pe_forward, 'x'),
    formatMetricValue(p.ps_ttm, 'x'),
    formatMetricValue(p.roe, '%'),
    p.comment || '-'
  ]);
  
  return renderGenericTable(doc, {
    startY,
    title: 'Peer Comparison',
    headers: ['Name', 'Ticker', 'Market Cap', 'PE (Fwd)', 'P/S', 'ROE', 'Comment'],
    rows,
    columnWidths: [110, 50, 70, 60, 50, 50, 105]
  });
}

/**
 * 财务概览表格
 */
function renderFinancialsOverview(doc, config = {}) {
  const { startY = 60, fundamentals = {}, growth = {} } = config;
  
  const latestRevenue = fundamentals.revenue_5y?.[fundamentals.revenue_5y?.length - 1]?.value;
  const latestEPS = fundamentals.eps_5y?.[fundamentals.eps_5y?.length - 1]?.value;
  
  const rows = [
    ['Revenue (TTM)', formatLargeNumber(latestRevenue)],
    ['Revenue 3Y CAGR', formatMetricValue(growth.revenue_cagr_3y, '%')],
    ['EPS (TTM)', formatMetricValue(latestEPS, '$')],
    ['EPS 3Y CAGR', formatMetricValue(growth.eps_cagr_3y, '%')],
    ['Gross Margin', formatMetricValue(fundamentals.gross_margin, '%')],
    ['Operating Margin', formatMetricValue(fundamentals.operating_margin, '%')],
    ['Net Margin', formatMetricValue(fundamentals.net_margin, '%')],
    ['ROE', formatMetricValue(fundamentals.roe, '%')],
    ['ROA', formatMetricValue(fundamentals.roa, '%')]
  ];
  
  return renderGenericTable(doc, {
    startY,
    title: 'Financial Overview',
    headers: ['Metric', 'Value'],
    rows,
    columnWidths: [250, 245]
  });
}

/**
 * 业务分部表格
 */
function renderSegmentTable(doc, config = {}) {
  const { startY = 60, segments = [] } = config;
  
  const defaultSegments = [
    { name: 'Primary Segment', revenue_pct: 60, growth: 'N/A', margin: 'N/A', comment: 'Main business' },
    { name: 'Secondary Segment', revenue_pct: 30, growth: 'N/A', margin: 'N/A', comment: 'Supporting business' },
    { name: 'Other', revenue_pct: 10, growth: 'N/A', margin: 'N/A', comment: 'Other operations' }
  ];
  
  const displaySegments = segments.length > 0 ? segments : defaultSegments;
  
  const rows = displaySegments.slice(0, 6).map(s => [
    s.name || s.segment,
    formatMetricValue(s.revenue_pct, '%'),
    s.growth || 'N/A',
    s.margin || 'N/A',
    s.comment || '-'
  ]);
  
  return renderGenericTable(doc, {
    startY,
    title: 'Business Segment Breakdown',
    headers: ['Segment', 'Revenue %', 'Growth', 'Margin', 'Comment'],
    rows,
    columnWidths: [130, 80, 80, 80, 125]
  });
}

/**
 * 投资策略表格
 */
function renderInvestmentStrategy(doc, config = {}) {
  const { startY = 60, price = {}, targets = {} } = config;
  
  const currentPrice = price.last || 100;
  const baseTarget = targets.base?.price || currentPrice * 1.1;
  const bullTarget = targets.bull?.price || baseTarget * 1.15;
  
  const rows = [
    ['Aggressive', `${formatMetricValue(currentPrice * 0.95, '$')} - ${formatMetricValue(currentPrice, '$')}`, formatMetricValue(bullTarget, '$'), formatMetricValue(currentPrice * 0.90, '$'), '5-10%', 'Higher risk tolerance'],
    ['Balanced', `${formatMetricValue(currentPrice * 0.97, '$')} - ${formatMetricValue(currentPrice * 1.02, '$')}`, formatMetricValue(baseTarget, '$'), formatMetricValue(currentPrice * 0.93, '$'), '3-7%', 'Core holding'],
    ['Conservative', `Below ${formatMetricValue(currentPrice * 0.95, '$')}`, formatMetricValue(baseTarget * 0.9, '$'), formatMetricValue(currentPrice * 0.88, '$'), '2-5%', 'Wait for pullback']
  ];
  
  return renderGenericTable(doc, {
    startY,
    title: 'Investment Strategy',
    headers: ['Profile', 'Entry Range', 'Target', 'Stop Loss', 'Position', 'Notes'],
    rows,
    columnWidths: [75, 100, 70, 70, 55, 125]
  });
}

/**
 * 场景分析表格
 */
function renderScenarioTargets(doc, config = {}) {
  const { startY = 60, targets = {}, price = {} } = config;
  
  const currentPrice = price.last || 100;
  
  const rows = [
    ['Bull Case', formatMetricValue(targets.bull?.price, '$'), formatMetricValue(targets.bull?.upside_pct, '%'), 'Accelerated growth, multiple expansion'],
    ['Base Case', formatMetricValue(targets.base?.price, '$'), formatMetricValue(targets.base?.upside_pct, '%'), 'Steady execution, in-line growth'],
    ['Bear Case', formatMetricValue(targets.bear?.price, '$'), formatMetricValue(targets.bear?.upside_pct || ((targets.bear?.price / currentPrice - 1) * 100), '%'), 'Slower growth, multiple contraction']
  ];
  
  return renderGenericTable(doc, {
    startY,
    title: 'Scenario Targets',
    headers: ['Scenario', 'Target Price', 'Upside/Downside', 'Assumptions'],
    rows,
    columnWidths: [100, 100, 100, 195]
  });
}

/**
 * 技术指标表格
 */
function renderTechnicalIndicators(doc, config = {}) {
  const { startY = 60, indicators = [] } = config;
  
  const defaultIndicators = [
    { indicator: 'RSI (14)', value: 'N/A', signal: 'Neutral' },
    { indicator: 'MACD', value: 'N/A', signal: 'Neutral' },
    { indicator: 'EMA 20', value: 'N/A', signal: 'Neutral' },
    { indicator: 'EMA 50', value: 'N/A', signal: 'Neutral' }
  ];
  
  const displayIndicators = indicators.length > 0 ? indicators : defaultIndicators;
  
  const rows = displayIndicators.map(i => [i.indicator, i.value, i.signal]);
  
  return renderGenericTable(doc, {
    startY,
    title: 'Technical Indicators',
    headers: ['Indicator', 'Value', 'Signal'],
    rows,
    columnWidths: [165, 165, 165]
  });
}

/**
 * 格式化指标值
 */
function formatMetricValue(value, suffix = '') {
  if (value === null || value === undefined || isNaN(value)) return 'N/A';
  if (suffix === '$') return `$${Number(value).toFixed(2)}`;
  if (suffix === '%') return `${Number(value).toFixed(1)}%`;
  if (suffix === 'x') return `${Number(value).toFixed(2)}x`;
  return Number(value).toFixed(2);
}

/**
 * 格式化大数字
 */
function formatLargeNumber(value) {
  if (value === null || value === undefined || isNaN(value)) return 'N/A';
  const num = Number(value);
  if (num >= 1e12) return `$${(num / 1e12).toFixed(2)}T`;
  if (num >= 1e9) return `$${(num / 1e9).toFixed(2)}B`;
  if (num >= 1e6) return `$${(num / 1e6).toFixed(2)}M`;
  return `$${num.toFixed(0)}`;
}

/**
 * 渲染页脚（简化版）
 */
function renderPageFooter(doc, config = {}) {
  const { pageNumber = 1, brand = 'USIS Research' } = config;
  
  // 分隔线
  doc.moveTo(50, doc.page.height - 60)
     .lineTo(doc.page.width - 50, doc.page.height - 60)
     .strokeColor('#e2e8f0').lineWidth(0.5).stroke();
  
  // 品牌名
  doc.fontSize(8).fillColor('#94a3b8');
  safeSetFont(doc, 'Regular');
  doc.text(brand, 50, doc.page.height - 50);
  
  // 页码
  doc.text(`Page ${pageNumber}`, doc.page.width - 100, doc.page.height - 50, { align: 'right' });
}

/**
 * 渲染法律免责声明页
 */
function renderDisclosuresPage(doc, config = {}) {
  const { startY = 60, firmName = 'USIS Research' } = config;
  
  let currentY = startY;
  
  // 标题
  doc.fontSize(18).fillColor('#1a2332');
  safeSetFont(doc, 'Bold');
  doc.text('Important Disclosures', 50, currentY);
  currentY += 35;
  
  const disclosures = [
    `This research report is published by ${firmName} for informational purposes only and is not intended to constitute investment advice.`,
    'The information contained herein has been obtained from sources believed to be reliable but is not guaranteed as to accuracy or completeness.',
    'Past performance is not indicative of future results. The value of investments and the income from them may fluctuate.',
    'Any opinions expressed are subject to change without notice and do not constitute a recommendation to buy or sell any security.',
    'This report may contain forward-looking statements that involve risks and uncertainties. Actual results may differ materially.',
    'The analyst(s) responsible for this report certify that the views expressed accurately reflect their personal views about the subject securities.',
    'Investors should consider this report as only a single factor in making their investment decision.',
    'This document is for the exclusive use of the recipient and may not be reproduced or redistributed without prior written consent.'
  ];
  
  doc.fontSize(9).fillColor('#374151');
  safeSetFont(doc, 'Regular');
  
  disclosures.forEach((text, i) => {
    doc.text(`${i + 1}. ${text}`, 50, currentY, { width: doc.page.width - 100 });
    currentY += doc.heightOfString(text, { width: doc.page.width - 100 }) + 12;
  });
  
  return currentY + 20;
}

module.exports = {
  renderProfessionalCover,
  renderTableOfContents,
  addHeader,
  addFooter,
  addPageHeaderFooter,
  renderInstitutionalHeader,
  extractSections,
  renderKeyTakeawaysSection,
  renderKeyMetricsRow,
  renderConsensusTable,
  renderSectionDivider,
  renderMetricCard,
  formatMetric,
  renderGenericTable,
  renderTwoColumnSection,
  renderChartFrame,
  renderBulletList,
  renderValuationSnapshot,
  renderPeerComparison,
  renderFinancialsOverview,
  renderSegmentTable,
  renderInvestmentStrategy,
  renderScenarioTargets,
  renderTechnicalIndicators,
  formatMetricValue,
  formatLargeNumber,
  renderPageFooter,
  renderDisclosuresPage
};
