/**
 * pdfTemplateUtils.js
 * 
 * Phase 6C: PDF 模板增强工具
 * 用于 Premium PDF - 专业封面、页眉、页脚、目录生成
 * 
 * 功能：
 * - 生成深蓝色机构级封面
 * - 添加页眉（USIS Institutional Research | SYMBOL | DATE）
 * - 添加页脚页码
 * - 自动生成目录（Table of Contents）
 */

/**
 * 安全设置字体（如果自定义字体不可用，回退到内置字体）
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {string} fontName - 字体名称（'Bold' 或 'Regular'）
 */
function safeSetFont(doc, fontName) {
  const hasBoldFont = doc._fontFamilies && doc._fontFamilies['Bold'];
  const hasRegularFont = doc._fontFamilies && doc._fontFamilies['Regular'];
  
  if (fontName === 'Bold') {
    doc.font(hasBoldFont ? 'Bold' : 'Helvetica-Bold');
  } else {
    doc.font(hasRegularFont ? 'Regular' : 'Helvetica');
  }
}

/**
 * 渲染专业封面页
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Object} report - 研报对象
 * @param {Object} options - 可选配置
 */
function renderProfessionalCover(doc, report, options = {}) {
  const {
    backgroundColor = '#1a2332', // 深蓝色背景
    accentColor = '#3b82f6',     // 蓝色强调
    textColor = '#ffffff',       // 白色文字
    logoPath = null              // 可选 logo 路径
  } = options;
  
  console.log(`\n📘 [PDFTemplateUtils] Rendering professional cover page...`);
  
  // 背景矩形（全页）
  doc.rect(0, 0, doc.page.width, doc.page.height)
     .fill(backgroundColor);
  
  // Logo（如果提供）
  if (logoPath) {
    try {
      doc.image(logoPath, 50, 50, { width: 100 });
    } catch (error) {
      console.warn(`⚠️  Logo load failed: ${error.message}`);
    }
  }
  
  // 机构名称（顶部）
  doc.fontSize(14).fillColor(accentColor);
  safeSetFont(doc, 'Bold');
  doc.text('USIS INSTITUTIONAL RESEARCH', 50, 120, { align: 'left' });
  
  // 分隔线
  doc.moveTo(50, 150)
     .lineTo(doc.page.width - 50, 150)
     .strokeColor(accentColor)
     .lineWidth(2)
     .stroke();
  
  // 主标题（股票代码）
  const symbol = report.symbol || 'N/A';
  doc.fontSize(56).fillColor(textColor);
  safeSetFont(doc, 'Bold');
  doc.text(symbol, 50, 220, { align: 'left' });
  
  // 副标题（公司名称或类型）
  const companyName = report.company_name || 'Equity Research Report';
  doc.fontSize(24).fillColor('#94a3b8'); // 浅灰色
  safeSetFont(doc, 'Regular');
  doc.text(companyName, 50, 300, { align: 'left', width: doc.page.width - 100 });
  
  // 报告类型标签
  doc.fontSize(14).fillColor(accentColor);
  safeSetFont(doc, 'Bold');
  doc.text('COMPREHENSIVE ANALYSIS REPORT', 50, 380, { align: 'left' });
  
  // 分析师信息
  const analyst = report.analyst || 'USIS Brain v7.0 Multi-AI System';
  doc.fontSize(12).fillColor('#94a3b8');
  safeSetFont(doc, 'Regular');
  doc.text(`Lead Analyst: ${analyst}`, 50, 420, { align: 'left' });
  
  // 评级（如果有）
  if (report.rating) {
    const ratingColors = {
      'Buy': '#10b981',
      'Strong Buy': '#059669',
      'Hold': '#f59e0b',
      'Sell': '#ef4444',
      'Strong Sell': '#dc2626'
    };
    
    const ratingColor = ratingColors[report.rating] || '#3b82f6';
    
    doc.fontSize(18).fillColor(ratingColor);
    safeSetFont(doc, 'Bold');
    doc.text(`Rating: ${report.rating}`, 50, 460, { align: 'left' });
  }
  
  // 目标价（如果有）
  if (report.targetPrice || report.target_price) {
    const target = report.targetPrice || report.target_price;
    doc.fontSize(16).fillColor(textColor);
    safeSetFont(doc, 'Bold');
    doc.text(`Target Price: ${target}`, 50, 500, { align: 'left' });
  }
  
  // 底部：日期和免责声明
  const reportDate = report.date || new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  doc.fontSize(12)
     .fillColor('#64748b')
  safeSetFont(doc, 'Regular');
  doc.text(reportDate, 50, doc.page.height - 150, { align: 'left' });
  
  doc.fontSize(9)
     .fillColor('#475569')
  doc.text(
       'This report is generated by USIS Brain v7.0 Multi-AI Research System.\n' +
       'For institutional use only. See full disclosures at the end of this report.',
       50,
       doc.page.height - 120,
       { align: 'left', width: doc.page.width - 100 }
     );
  
  // 底部装饰线
  doc.moveTo(50, doc.page.height - 50)
     .lineTo(doc.page.width - 50, doc.page.height - 50)
     .strokeColor(accentColor)
     .lineWidth(1)
     .stroke();
  
  console.log(`✅ [PDFTemplateUtils] Cover page rendered`);
  
  // 新页面开始正文
  doc.addPage();
}

/**
 * 生成目录（Table of Contents）
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {Array} sections - 章节数组 [{title, page}]
 * @param {Object} options - 可选配置
 */
function renderTableOfContents(doc, sections, options = {}) {
  const {
    title = 'Table of Contents',
    startY = 100
  } = options;
  
  console.log(`\n📑 [PDFTemplateUtils] Rendering table of contents (${sections.length} sections)...`);
  
  // 标题
  doc.fontSize(24)
     .fillColor('#1a2332')
  safeSetFont(doc, 'Bold');
  doc.text(title, 50, startY, { align: 'left' });
  
  // 分隔线
  doc.moveTo(50, startY + 40)
     .lineTo(doc.page.width - 50, startY + 40)
     .strokeColor('#3b82f6')
     .lineWidth(2)
     .stroke();
  
  let currentY = startY + 70;
  
  // 遍历章节
  sections.forEach((section, index) => {
    // 检查是否需要分页
    if (currentY > doc.page.height - 100) {
      doc.addPage();
      currentY = 80;
    }
    
    // 章节编号
    const sectionNumber = (index + 1).toString().padStart(2, '0');
    doc.fontSize(12)
       .fillColor('#64748b')
  safeSetFont(doc, 'Bold');
  doc.text(sectionNumber, 50, currentY, { width: 30, continued: false });
    
    // 章节标题
    doc.fontSize(12)
       .fillColor('#1a2332')
  safeSetFont(doc, 'Regular');
  doc.text(section.title, 90, currentY, { width: doc.page.width - 200, continued: false });
    
    // 页码（右对齐）
    const pageNum = section.page || (index + 2);
    doc.fontSize(12)
       .fillColor('#64748b')
  safeSetFont(doc, 'Regular');
  doc.text(pageNum.toString(), doc.page.width - 100, currentY, { width: 50, align: 'right' });
    
    // 虚线连接
    const dotY = currentY + 5;
    for (let x = 90 + doc.widthOfString(section.title) + 10; x < doc.page.width - 110; x += 5) {
      doc.circle(x, dotY, 0.5).fill('#cbd5e1');
    }
    
    currentY += 25;
  });
  
  console.log(`✅ [PDFTemplateUtils] Table of contents rendered`);
  
  // 新页面开始正文
  doc.addPage();
}

/**
 * 添加页眉
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {string} symbol - 股票代码
 * @param {number} pageNumber - 页码
 * @param {Object} options - 可选配置
 */
function addHeader(doc, symbol, pageNumber, options = {}) {
  const {
    showOnFirstPage = false,
    headerText = 'USIS Institutional Research'
  } = options;
  
  // 第一页通常不显示页眉（封面）
  if (pageNumber === 1 && !showOnFirstPage) {
    return;
  }
  
  const currentY = doc.y; // 保存当前 Y 位置
  
  // 页眉文字
  doc.fontSize(9)
     .fillColor('#64748b')
  safeSetFont(doc, 'Regular');
  doc.text(
       `${headerText} | ${symbol} | ${new Date().toLocaleDateString('en-US')}`,
       50,
       30,
       { align: 'center', width: doc.page.width - 100 }
     );
  
  // 页眉分隔线
  doc.moveTo(50, 45)
     .lineTo(doc.page.width - 50, 45)
     .strokeColor('#e2e8f0')
     .lineWidth(0.5)
     .stroke();
  
  // 恢复 Y 位置
  doc.y = currentY;
}

/**
 * 添加页脚（页码）
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {number} pageNumber - 页码
 * @param {number} totalPages - 总页数
 * @param {Object} options - 可选配置
 */
function addFooter(doc, pageNumber, totalPages, options = {}) {
  const {
    showOnFirstPage = false,
    includeDisclaimer = true
  } = options;
  
  // 第一页通常不显示页脚（封面）
  if (pageNumber === 1 && !showOnFirstPage) {
    return;
  }
  
  // 页脚分隔线
  doc.moveTo(50, doc.page.height - 70)
     .lineTo(doc.page.width - 50, doc.page.height - 70)
     .strokeColor('#e2e8f0')
     .lineWidth(0.5)
     .stroke();
  
  // 页码（居中）
  doc.fontSize(9)
     .fillColor('#64748b')
  safeSetFont(doc, 'Regular');
  doc.text(
       `Page ${pageNumber} of ${totalPages}`,
       50,
       doc.page.height - 55,
       { align: 'center', width: doc.page.width - 100 }
     );
  
  // 免责声明（可选）
  if (includeDisclaimer) {
    doc.fontSize(7)
       .fillColor('#94a3b8')
  doc.text(
         'Confidential - For institutional use only',
         50,
         doc.page.height - 35,
         { align: 'center', width: doc.page.width - 100 }
       );
  }
}

/**
 * 自动为 PDF 文档添加页眉页脚（简化版 - 不使用事件监听）
 * 注意：PDFKit 不支持自动页眉页脚，需要手动调用
 * @param {PDFDocument} doc - PDFKit 文档对象
 * @param {string} symbol - 股票代码
 * @param {number} currentPage - 当前页码
 * @param {number} totalPages - 总页数
 * @param {Object} options - 可选配置
 */
function addPageHeaderFooter(doc, symbol, currentPage, totalPages, options = {}) {
  addHeader(doc, symbol, currentPage, options);
  addFooter(doc, currentPage, totalPages, options);
}

/**
 * 提取章节结构（用于目录生成）
 * @param {Object} report - 研报对象
 * @returns {Array} 章节数组 [{title, page}]
 */
function extractSections(report) {
  const sections = [];
  
  if (report.sections && Array.isArray(report.sections)) {
    report.sections.forEach((section, index) => {
      sections.push({
        title: section.title || section.heading || `Section ${index + 1}`,
        page: index + 2 // 假设封面是第1页，目录是第2页
      });
    });
  } else if (report.sections && typeof report.sections === 'object') {
    // 如果 sections 是对象
    Object.keys(report.sections).forEach((key, index) => {
      sections.push({
        title: report.sections[key].title || key,
        page: index + 2
      });
    });
  }
  
  return sections;
}

module.exports = {
  renderProfessionalCover,
  renderTableOfContents,
  addHeader,
  addFooter,
  addPageHeaderFooter,
  extractSections
};
