/**
 * ═══════════════════════════════════════════════════════════════
 * USIS Brain v7.0 - Telegram PDF Utility
 * ═══════════════════════════════════════════════════════════════
 * 
 * 功能：Telegram PDF 文档发送
 * - 支持 Buffer 上传
 * - 自动文件名和 Caption 格式化
 * - 错误处理和重试逻辑
 * 
 * @author USIS Brain v7 Agent
 * @created 2024-11-24
 */

const fs = require('fs');
const path = require('path');

/**
 * 发送 PDF 文档到 Telegram
 * @param {number} chatId - 聊天 ID
 * @param {Buffer} pdfBuffer - PDF Buffer
 * @param {string} filename - 文件名（如 NVDA_Equity_Research_USISv7.pdf）
 * @param {string} caption - 说明文字
 * @param {Object} bot - Telegram Bot 实例
 * @returns {Promise<Object>} Telegram API 响应
 */
async function sendPdfReport(chatId, pdfBuffer, filename, caption, bot) {
  console.log(`\n📤 [TelegramPdf] Sending PDF document`);
  console.log(`   ├─ Chat ID: ${chatId}`);
  console.log(`   ├─ Filename: ${filename}`);
  console.log(`   ├─ Size: ${(pdfBuffer.length / 1024).toFixed(2)} KB`);
  console.log(`   └─ Caption: ${caption.substring(0, 50)}...`);
  
  try {
    // 验证输入
    if (!pdfBuffer || !Buffer.isBuffer(pdfBuffer)) {
      throw new Error('Invalid PDF buffer provided');
    }
    
    if (pdfBuffer.length === 0) {
      throw new Error('PDF buffer is empty');
    }
    
    if (pdfBuffer.length > 50 * 1024 * 1024) {
      throw new Error('PDF too large (>50MB). Telegram limit exceeded.');
    }
    
    // 发送文档（使用 Buffer）
    const result = await bot.sendDocument(
      chatId,
      pdfBuffer,
      {
        caption: caption,
        parse_mode: 'Markdown'
      },
      {
        filename: filename,
        contentType: 'application/pdf'
      }
    );
    
    console.log(`✅ [TelegramPdf] PDF sent successfully`);
    console.log(`   └─ Message ID: ${result.message_id}\n`);
    
    return result;
    
  } catch (error) {
    console.error(`\n❌ [TelegramPdf] Failed to send PDF`);
    console.error(`   ├─ Error: ${error.message}`);
    console.error(`   └─ Stack: ${error.stack.substring(0, 200)}...\n`);
    
    // 更友好的错误消息
    const errorMessage = getFriendlyErrorMessage(error);
    throw new Error(errorMessage);
  }
}

/**
 * 生成 PDF 文件名
 * @param {string} symbol - 股票代码
 * @param {string} language - 语言
 * @returns {string} 文件名
 */
function generatePdfFilename(symbol, language = 'en') {
  const timestamp = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
  const langSuffix = language !== 'en' ? `_${language.toUpperCase()}` : '';
  return `${symbol.toUpperCase()}_Equity_Research_USISv7${langSuffix}_${timestamp}.pdf`;
}

/**
 * 生成 PDF Caption
 * @param {string} symbol - 股票代码
 * @param {string} language - 语言
 * @returns {string} Caption 文字
 */
function generatePdfCaption(symbol, language = 'en') {
  const captions = {
    en: `📄 *${symbol.toUpperCase()} · Equity Research Report*\n\n` +
        `Generated by USIS Brain v7.0 Multi-AI Research System\n` +
        `Language: English\n` +
        `Format: PDF (Institutional Grade)`,
    
    zh: `📄 *${symbol.toUpperCase()} · 股票研究报告*\n\n` +
        `由 USIS Brain v7.0 多 AI 研究系统生成\n` +
        `语言：中文\n` +
        `格式：PDF（机构级）`,
    
    es: `📄 *${symbol.toUpperCase()} · Informe de Investigación*\n\n` +
        `Generado por USIS Brain v7.0 Sistema Multi-AI\n` +
        `Idioma: Español\n` +
        `Formato: PDF (Nivel Institucional)`
  };
  
  return captions[language] || captions['en'];
}

/**
 * 获取友好的错误消息
 * @param {Error} error - 错误对象
 * @returns {string} 友好的错误消息
 */
function getFriendlyErrorMessage(error) {
  const message = error.message.toLowerCase();
  
  if (message.includes('file too large') || message.includes('too big')) {
    return 'PDF file too large (>50MB). Please try a shorter report or text format.';
  }
  
  if (message.includes('timeout')) {
    return 'Upload timeout. Please check your network connection and try again.';
  }
  
  if (message.includes('forbidden') || message.includes('403')) {
    return 'Bot lacks permission to send files. Please check bot settings.';
  }
  
  if (message.includes('not found') || message.includes('404')) {
    return 'Chat not found. Please start the bot first.';
  }
  
  // 默认错误
  return `Failed to send PDF: ${error.message}`;
}

/**
 * 保存 PDF 到临时文件（用于调试）
 * @param {Buffer} pdfBuffer - PDF Buffer
 * @param {string} filename - 文件名
 * @returns {string} 保存的文件路径
 */
function savePdfToTempFile(pdfBuffer, filename) {
  const tempDir = path.join(__dirname, '..', 'tmp');
  
  // 创建 tmp 目录（如果不存在）
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
  }
  
  const filePath = path.join(tempDir, filename);
  fs.writeFileSync(filePath, pdfBuffer);
  
  console.log(`💾 [TelegramPdf] PDF saved to: ${filePath}`);
  return filePath;
}

// ═══════════════════════════════════════════════════════════════
// 模块导出
// ═══════════════════════════════════════════════════════════════

module.exports = {
  sendPdfReport,
  generatePdfFilename,
  generatePdfCaption,
  savePdfToTempFile
};
